pipeline {
    agent any

    stages {
         stage('SonarQube analysis') {
            agent {
                docker {
                  image 'sonarsource/sonar-scanner-cli:4.7.0'
                }
               }
               environment {
        CI = 'true'
        //  scannerHome = tool 'Sonar'
        scannerHome='/opt/sonar-scanner'
    }
            steps{
                withSonarQubeEnv('Sonar') {
                    sh "${scannerHome}/bin/sonar-scanner"
                }
            }
        }
        stage('Build') {
            steps {
                // Install dependencies and build your application
                sh '''
                ls
                cat sonar-project.properties
                '''
            }
        }

       

        
    }

    post {
        always {
            // Archive artifacts or perform cleanup actions here
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
        }

        success {
            // Actions to take if the pipeline succeeds
            echo 'Pipeline succeeded!'
        }

        failure {
            // Actions to take if the pipeline fails
            echo 'Pipeline is  failed!'
        }
    }
}
